# Generated by Django 2.2.5 on 2019-10-15 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeWebPortal', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('number', 'department')},
        ),
    ]
