# Generated by Django 2.2.5 on 2019-11-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeWebPortal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('ER', 'Enrolled'), ('DR', 'Dropped'), ('IC', 'In Cart'), ('SA', 'Saved')], default='ER', max_length=2),
        ),
    ]
