# Generated by Django 2.2.5 on 2019-10-31 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeWebPortal', '0002_auto_20191030_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='number',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=8),
        ),
    ]
