# Generated by Django 2.2.5 on 2019-10-29 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegeWebPortal', '0002_auto_20191015_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='collegeWebPortal.Course')),
                ('num', models.IntegerField()),
                ('status', models.BooleanField()),
                ('semester', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=50)),
            ],
            bases=('collegeWebPortal.course',),
        ),
    ]
